# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc36.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 525)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Button4 = QtWidgets.QPushButton(self.centralwidget)
        self.Button4.setGeometry(QtCore.QRect(200, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button4.setFont(font)
        self.Button4.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button4.setObjectName("Button4")
        self.Button0 = QtWidgets.QPushButton(self.centralwidget)
        self.Button0.setGeometry(QtCore.QRect(0, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button0.setFont(font)
        self.Button0.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button0.setObjectName("Button0")
        self.Button9 = QtWidgets.QPushButton(self.centralwidget)
        self.Button9.setGeometry(QtCore.QRect(200, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button9.setFont(font)
        self.Button9.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button9.setObjectName("Button9")
        self.Button8 = QtWidgets.QPushButton(self.centralwidget)
        self.Button8.setGeometry(QtCore.QRect(150, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button8.setFont(font)
        self.Button8.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button8.setObjectName("Button8")
        self.Button6 = QtWidgets.QPushButton(self.centralwidget)
        self.Button6.setGeometry(QtCore.QRect(50, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button6.setFont(font)
        self.Button6.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button6.setObjectName("Button6")
        self.Button1 = QtWidgets.QPushButton(self.centralwidget)
        self.Button1.setGeometry(QtCore.QRect(50, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button1.setFont(font)
        self.Button1.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button1.setObjectName("Button1")
        self.Button3 = QtWidgets.QPushButton(self.centralwidget)
        self.Button3.setGeometry(QtCore.QRect(150, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button3.setFont(font)
        self.Button3.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button3.setObjectName("Button3")
        self.Button7 = QtWidgets.QPushButton(self.centralwidget)
        self.Button7.setGeometry(QtCore.QRect(100, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button7.setFont(font)
        self.Button7.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button7.setObjectName("Button7")
        self.ButtonBack = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonBack.setGeometry(QtCore.QRect(350, 50, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonBack.setFont(font)
        self.ButtonBack.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonBack.setObjectName("ButtonBack")
        self.ButtonT = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonT.setGeometry(QtCore.QRect(300, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonT.setFont(font)
        self.ButtonT.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonT.setObjectName("ButtonT")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 351, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ButtonDel = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDel.setGeometry(QtCore.QRect(350, 0, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonDel.setFont(font)
        self.ButtonDel.setStyleSheet("background-color: rgb(255, , 0);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonDel.setObjectName("ButtonDel")
        self.Button5 = QtWidgets.QPushButton(self.centralwidget)
        self.Button5.setGeometry(QtCore.QRect(0, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button5.setFont(font)
        self.Button5.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button5.setObjectName("Button5")
        self.Button2 = QtWidgets.QPushButton(self.centralwidget)
        self.Button2.setGeometry(QtCore.QRect(100, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Button2.setFont(font)
        self.Button2.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Button2.setObjectName("Button2")
        self.ButtonC = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonC.setGeometry(QtCore.QRect(100, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonC.setFont(font)
        self.ButtonC.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonC.setObjectName("ButtonC")
        self.ButtonE = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonE.setGeometry(QtCore.QRect(200, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonE.setFont(font)
        self.ButtonE.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonE.setObjectName("ButtonE")
        self.ButtonI = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonI.setGeometry(QtCore.QRect(0, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonI.setFont(font)
        self.ButtonI.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonI.setObjectName("ButtonI")
        self.ButtonB = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonB.setGeometry(QtCore.QRect(50, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonB.setFont(font)
        self.ButtonB.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonB.setObjectName("ButtonB")
        self.ButtonA = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonA.setGeometry(QtCore.QRect(0, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonA.setFont(font)
        self.ButtonA.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonA.setObjectName("ButtonA")
        self.ButtonH = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonH.setGeometry(QtCore.QRect(350, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonH.setFont(font)
        self.ButtonH.setStyleSheet("background-color: rgb(200, , 200);\n"
"")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonH.setObjectName("ButtonH")
        self.ButtonJ = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonJ.setGeometry(QtCore.QRect(50, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonJ.setFont(font)
        self.ButtonJ.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonJ.setObjectName("ButtonJ")
        self.ButtonF_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonF_2.setGeometry(QtCore.QRect(250, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonF_2.setFont(font)
        self.ButtonF_2.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonF_2.setObjectName("ButtonF_2")
        self.ButtonG = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonG.setGeometry(QtCore.QRect(300, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonG.setFont(font)
        self.ButtonG.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonG.setObjectName("ButtonG")
        self.ButtonD = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonD.setGeometry(QtCore.QRect(150, 250, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonD.setFont(font)
        self.ButtonD.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonD.setObjectName("ButtonD")
        self.ButtonM = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonM.setGeometry(QtCore.QRect(200, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonM.setFont(font)
        self.ButtonM.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonM.setObjectName("ButtonM")
        self.ButtonO = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonO.setGeometry(QtCore.QRect(300, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonO.setFont(font)
        self.ButtonO.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonO.setObjectName("ButtonO")
        self.ButtonS = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonS.setGeometry(QtCore.QRect(100, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonS.setFont(font)
        self.ButtonS.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonS.setObjectName("ButtonS")
        self.ButtonL = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonL.setGeometry(QtCore.QRect(150, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonL.setFont(font)
        self.ButtonL.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonL.setObjectName("ButtonL")
        self.ButtonK = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonK.setGeometry(QtCore.QRect(100, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonK.setFont(font)
        self.ButtonK.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonK.setObjectName("ButtonK")
        self.ButtonR = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonR.setGeometry(QtCore.QRect(50, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonR.setFont(font)
        self.ButtonR.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonR.setObjectName("ButtonR")
        self.ButtonT_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonT_2.setGeometry(QtCore.QRect(150, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonT_2.setFont(font)
        self.ButtonT_2.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonT_2.setObjectName("ButtonT_2")
        self.ButtonP = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonP.setGeometry(QtCore.QRect(350, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonP.setFont(font)
        self.ButtonP.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonP.setObjectName("ButtonP")
        self.ButtonQ = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonQ.setGeometry(QtCore.QRect(0, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonQ.setFont(font)
        self.ButtonQ.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonQ.setObjectName("ButtonQ")
        self.ButtonN = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonN.setGeometry(QtCore.QRect(250, 300, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonN.setFont(font)
        self.ButtonN.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonN.setObjectName("ButtonN")
        self.ButtonW = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonW.setGeometry(QtCore.QRect(300, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonW.setFont(font)
        self.ButtonW.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonW.setObjectName("ButtonW")
        self.ButtonY = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonY.setGeometry(QtCore.QRect(0, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonY.setFont(font)
        self.ButtonY.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonY.setObjectName("ButtonY")
        self.ButtonV = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonV.setGeometry(QtCore.QRect(250, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonV.setFont(font)
        self.ButtonV.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonV.setObjectName("ButtonV")
        self.ButtonU = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonU.setGeometry(QtCore.QRect(200, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonU.setFont(font)
        self.ButtonU.setStyleSheet("background-color: rgb(200, , 200);\n"
"")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonU.setObjectName("ButtonU")
        self.ButtonZ = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonZ.setGeometry(QtCore.QRect(50, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonZ.setFont(font)
        self.ButtonZ.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonZ.setObjectName("ButtonZ")
        self.ButtonX = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonX.setGeometry(QtCore.QRect(350, 350, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonX.setFont(font)
        self.ButtonX.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonX.setObjectName("ButtonX")
        self.ButtonDiv = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDiv.setGeometry(QtCore.QRect(350, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonDiv.setFont(font)
        self.ButtonDiv.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonDiv.setObjectName("ButtonDiv")
        self.ButtonATg = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonATg.setGeometry(QtCore.QRect(250, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonATg.setFont(font)
        self.ButtonATg.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonATg.setObjectName("ButtonATg")
        self.ButtonDelenie = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDelenie.setGeometry(QtCore.QRect(250, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonDelenie.setFont(font)
        self.ButtonDelenie.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonDelenie.setObjectName("ButtonDelenie")
        self.ButtonCos = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonCos.setGeometry(QtCore.QRect(100, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonCos.setFont(font)
        self.ButtonCos.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonCos.setObjectName("ButtonCos")
        self.ButtonRavno = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonRavno.setGeometry(QtCore.QRect(350, 400, 50, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonRavno.setFont(font)
        self.ButtonRavno.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonRavno.setObjectName("ButtonRavno")
        self.ButtonASin = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonASin.setGeometry(QtCore.QRect(50, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonASin.setFont(font)
        self.ButtonASin.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonASin.setObjectName("ButtonASin")
        self.Buttonlog2 = QtWidgets.QPushButton(self.centralwidget)
        self.Buttonlog2.setGeometry(QtCore.QRect(100, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Buttonlog2.setFont(font)
        self.Buttonlog2.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Buttonlog2.setObjectName("Buttonlog2")
        self.ButtonS1 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonS1.setGeometry(QtCore.QRect(0, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonS1.setFont(font)
        self.ButtonS1.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonS1.setObjectName("ButtonS1")
        self.ButtonACos = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonACos.setGeometry(QtCore.QRect(150, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonACos.setFont(font)
        self.ButtonACos.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonACos.setObjectName("ButtonACos")
        self.ButtonMod = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonMod.setGeometry(QtCore.QRect(300, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonMod.setFont(font)
        self.ButtonMod.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonMod.setObjectName("ButtonMod")
        self.ButtonPi = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonPi.setGeometry(QtCore.QRect(250, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonPi.setFont(font)
        self.ButtonPi.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonPi.setObjectName("ButtonPi")
        self.ButtonSquare = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSquare.setGeometry(QtCore.QRect(250, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonSquare.setFont(font)
        self.ButtonSquare.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonSquare.setObjectName("ButtonSquare")
        self.ButtonProizvedenie = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonProizvedenie.setGeometry(QtCore.QRect(200, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonProizvedenie.setFont(font)
        self.ButtonProizvedenie.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonProizvedenie.setObjectName("ButtonProizvedenie")
        self.ButtonSqrt = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSqrt.setGeometry(QtCore.QRect(250, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonSqrt.setFont(font)
        self.ButtonSqrt.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonSqrt.setObjectName("ButtonSqrt")
        self.ButtonSin = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSin.setGeometry(QtCore.QRect(0, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonSin.setFont(font)
        self.ButtonSin.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonSin.setObjectName("ButtonSin")
        self.ButtonS2 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonS2.setGeometry(QtCore.QRect(50, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonS2.setFont(font)
        self.ButtonS2.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonS2.setObjectName("ButtonS2")
        self.ButtonTg = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonTg.setGeometry(QtCore.QRect(200, 450, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonTg.setFont(font)
        self.ButtonTg.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonTg.setObjectName("ButtonTg")
        self.ButtonF = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonF.setGeometry(QtCore.QRect(300, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonF.setFont(font)
        self.ButtonF.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonF.setObjectName("ButtonF")
        self.ButtonRaznica = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonRaznica.setGeometry(QtCore.QRect(150, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonRaznica.setFont(font)
        self.ButtonRaznica.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonRaznica.setObjectName("ButtonRaznica")
        self.ButtonSumma = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSumma.setGeometry(QtCore.QRect(100, 100, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ButtonSumma.setFont(font)
        self.ButtonSumma.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonSumma.setObjectName("ButtonSumma")
        self.ButtonCube = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonCube.setGeometry(QtCore.QRect(300, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonCube.setFont(font)
        self.ButtonCube.setStyleSheet("background-color: rgb(200, , 200);\n"
"")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonCube.setObjectName("ButtonCube")
        self.ButtonStepen = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonStepen.setGeometry(QtCore.QRect(350, 150, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonStepen.setFont(font)
        self.ButtonStepen.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonStepen.setObjectName("ButtonStepen")
        self.ButtonSqrt_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSqrt_2.setGeometry(QtCore.QRect(300, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonSqrt_2.setFont(font)
        self.ButtonSqrt_2.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonSqrt_2.setObjectName("ButtonSqrt_2")
        self.ButtonSqrt_3 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSqrt_3.setGeometry(QtCore.QRect(350, 200, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ButtonSqrt_3.setFont(font)
        self.ButtonSqrt_3.setStyleSheet("background-color: rgb(200, , 200);\n"
"")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.ButtonSqrt_3.setObjectName("ButtonSqrt_3")
        self.Buttonlog2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Buttonlog2_2.setGeometry(QtCore.QRect(150, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Buttonlog2_2.setFont(font)
        self.Buttonlog2_2.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Buttonlog2_2.setObjectName("Buttonlog2_2")
        self.Buttonlog2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Buttonlog2_3.setGeometry(QtCore.QRect(200, 400, 50, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Buttonlog2_3.setFont(font)
        self.Buttonlog2_3.setStyleSheet("background-color: rgb(200, , 200);")
        # отсутствие второго параметра цветовой составляещей, для красоты
        self.Buttonlog2_3.setObjectName("Buttonlog2_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        MainWindow.setMenuBar(self.menubar)
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.action4 = QtWidgets.QAction(MainWindow)
        self.action4.setObjectName("action4")
        self.action5 = QtWidgets.QAction(MainWindow)
        self.action5.setObjectName("action5")
        self.action6 = QtWidgets.QAction(MainWindow)
        self.action6.setObjectName("action6")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action8 = QtWidgets.QAction(MainWindow)
        self.action8.setObjectName("action8")
        self.action10 = QtWidgets.QAction(MainWindow)
        self.action10.setObjectName("action10")
        self.action16 = QtWidgets.QAction(MainWindow)
        self.action16.setObjectName("action16")
        self.action2_3 = QtWidgets.QAction(MainWindow)
        self.action2_3.setObjectName("action2_3")
        self.action3_2 = QtWidgets.QAction(MainWindow)
        self.action3_2.setObjectName("action3_2")
        self.action4_2 = QtWidgets.QAction(MainWindow)
        self.action4_2.setObjectName("action4_2")
        self.action5_2 = QtWidgets.QAction(MainWindow)
        self.action5_2.setObjectName("action5_2")
        self.action6_2 = QtWidgets.QAction(MainWindow)
        self.action6_2.setObjectName("action6_2")
        self.action7 = QtWidgets.QAction(MainWindow)
        self.action7.setObjectName("action7")
        self.action8_2 = QtWidgets.QAction(MainWindow)
        self.action8_2.setObjectName("action8_2")
        self.action9 = QtWidgets.QAction(MainWindow)
        self.action9.setObjectName("action9")
        self.action10_2 = QtWidgets.QAction(MainWindow)
        self.action10_2.setObjectName("action10_2")
        self.action11 = QtWidgets.QAction(MainWindow)
        self.action11.setObjectName("action11")
        self.action12 = QtWidgets.QAction(MainWindow)
        self.action12.setObjectName("action12")
        self.action13 = QtWidgets.QAction(MainWindow)
        self.action13.setObjectName("action13")
        self.action14 = QtWidgets.QAction(MainWindow)
        self.action14.setObjectName("action14")
        self.action15 = QtWidgets.QAction(MainWindow)
        self.action15.setObjectName("action15")
        self.action16_2 = QtWidgets.QAction(MainWindow)
        self.action16_2.setObjectName("action16_2")
        self.action17 = QtWidgets.QAction(MainWindow)
        self.action17.setObjectName("action17")
        self.action18 = QtWidgets.QAction(MainWindow)
        self.action18.setObjectName("action18")
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action20 = QtWidgets.QAction(MainWindow)
        self.action20.setObjectName("action20")
        self.action21 = QtWidgets.QAction(MainWindow)
        self.action21.setObjectName("action21")
        self.action22 = QtWidgets.QAction(MainWindow)
        self.action22.setObjectName("action22")
        self.action23 = QtWidgets.QAction(MainWindow)
        self.action23.setObjectName("action23")
        self.action24 = QtWidgets.QAction(MainWindow)
        self.action24.setObjectName("action24")
        self.action25 = QtWidgets.QAction(MainWindow)
        self.action25.setObjectName("action25")
        self.action26 = QtWidgets.QAction(MainWindow)
        self.action26.setObjectName("action26")
        self.action27 = QtWidgets.QAction(MainWindow)
        self.action27.setObjectName("action27")
        self.action28 = QtWidgets.QAction(MainWindow)
        self.action28.setObjectName("action28")
        self.action29 = QtWidgets.QAction(MainWindow)
        self.action29.setObjectName("action29")
        self.action30 = QtWidgets.QAction(MainWindow)
        self.action30.setObjectName("action30")
        self.action31 = QtWidgets.QAction(MainWindow)
        self.action31.setObjectName("action31")
        self.action30_2 = QtWidgets.QAction(MainWindow)
        self.action30_2.setObjectName("action30_2")
        self.action1_2 = QtWidgets.QAction(MainWindow)
        self.action1_2.setObjectName("action1_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_10 = QtWidgets.QAction(MainWindow)
        self.action_10.setObjectName("action_10")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action2_2)
        self.menu.addAction(self.action8)
        self.menu.addAction(self.action10)
        self.menu.addAction(self.action16)
        self.menu.addAction(self.action_4)
        self.menu_4.addAction(self.action_6)
        self.menu_4.addAction(self.action_9)
        self.menu_4.addAction(self.action_10)
        self.menu_4.addAction(self.action)
        self.menu_4.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.Button0.setText(_translate("MainWindow", "0"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.ButtonBack.setText(_translate("MainWindow", "<--"))
        self.ButtonT.setText(_translate("MainWindow", "."))
        self.label.setText(_translate("MainWindow", "___________________________________"))
        self.ButtonDel.setText(_translate("MainWindow", "С"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.ButtonC.setText(_translate("MainWindow", "C"))
        self.ButtonE.setText(_translate("MainWindow", "E"))
        self.ButtonI.setText(_translate("MainWindow", "I"))
        self.ButtonB.setText(_translate("MainWindow", "B"))
        self.ButtonA.setText(_translate("MainWindow", "A"))
        self.ButtonH.setText(_translate("MainWindow", "H"))
        self.ButtonJ.setText(_translate("MainWindow", "J"))
        self.ButtonF_2.setText(_translate("MainWindow", "F"))
        self.ButtonG.setText(_translate("MainWindow", "G"))
        self.ButtonD.setText(_translate("MainWindow", "D"))
        self.ButtonM.setText(_translate("MainWindow", "M"))
        self.ButtonO.setText(_translate("MainWindow", "O"))
        self.ButtonS.setText(_translate("MainWindow", "S"))
        self.ButtonL.setText(_translate("MainWindow", "L"))
        self.ButtonK.setText(_translate("MainWindow", "K"))
        self.ButtonR.setText(_translate("MainWindow", "R"))
        self.ButtonT_2.setText(_translate("MainWindow", "T"))
        self.ButtonP.setText(_translate("MainWindow", "P"))
        self.ButtonQ.setText(_translate("MainWindow", "Q"))
        self.ButtonN.setText(_translate("MainWindow", "N"))
        self.ButtonW.setText(_translate("MainWindow", "W"))
        self.ButtonY.setText(_translate("MainWindow", "Y"))
        self.ButtonV.setText(_translate("MainWindow", "V"))
        self.ButtonU.setText(_translate("MainWindow", "U"))
        self.ButtonZ.setText(_translate("MainWindow", "Z"))
        self.ButtonX.setText(_translate("MainWindow", "X"))
        self.ButtonDiv.setText(_translate("MainWindow", "div"))
        self.ButtonATg.setText(_translate("MainWindow", "atan"))
        self.ButtonDelenie.setText(_translate("MainWindow", "/"))
        self.ButtonCos.setText(_translate("MainWindow", "cos"))
        self.ButtonRavno.setText(_translate("MainWindow", "="))
        self.ButtonASin.setText(_translate("MainWindow", "asin"))
        self.Buttonlog2.setText(_translate("MainWindow", "log2"))
        self.ButtonS1.setText(_translate("MainWindow", "("))
        self.ButtonACos.setText(_translate("MainWindow", "acos"))
        self.ButtonMod.setText(_translate("MainWindow", "mod"))
        self.ButtonPi.setText(_translate("MainWindow", "pi"))
        self.ButtonSquare.setText(_translate("MainWindow", "x^2"))
        self.ButtonProizvedenie.setText(_translate("MainWindow", "x"))
        self.ButtonSqrt.setText(_translate("MainWindow", "√"))
        self.ButtonSin.setText(_translate("MainWindow", "sin"))
        self.ButtonS2.setText(_translate("MainWindow", ")"))
        self.ButtonTg.setText(_translate("MainWindow", "tan"))
        self.ButtonF.setText(_translate("MainWindow", "!"))
        self.ButtonRaznica.setText(_translate("MainWindow", "-"))
        self.ButtonSumma.setText(_translate("MainWindow", "+"))
        self.ButtonCube.setText(_translate("MainWindow", "x^3"))
        self.ButtonStepen.setText(_translate("MainWindow", "x^y"))
        self.ButtonSqrt_2.setText(_translate("MainWindow", "3√"))
        self.ButtonSqrt_3.setText(_translate("MainWindow", "y√"))
        self.Buttonlog2_2.setText(_translate("MainWindow", "log10"))
        self.Buttonlog2_3.setText(_translate("MainWindow", "logX"))
        self.menu.setTitle(_translate("MainWindow", "Выбрать систему счисления"))
        self.menu_4.setTitle(_translate("MainWindow", "Конвентор"))
        self.action2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.action4.setText(_translate("MainWindow", "4"))
        self.action5.setText(_translate("MainWindow", "5"))
        self.action6.setText(_translate("MainWindow", "6"))
        self.action2_2.setText(_translate("MainWindow", "2"))
        self.action8.setText(_translate("MainWindow", "8"))
        self.action10.setText(_translate("MainWindow", "10"))
        self.action16.setText(_translate("MainWindow", "16"))
        self.action2_3.setText(_translate("MainWindow", "2"))
        self.action3_2.setText(_translate("MainWindow", "3"))
        self.action4_2.setText(_translate("MainWindow", "4"))
        self.action5_2.setText(_translate("MainWindow", "5"))
        self.action6_2.setText(_translate("MainWindow", "6"))
        self.action7.setText(_translate("MainWindow", "7"))
        self.action8_2.setText(_translate("MainWindow", "8"))
        self.action9.setText(_translate("MainWindow", "9"))
        self.action10_2.setText(_translate("MainWindow", "10"))
        self.action11.setText(_translate("MainWindow", "11"))
        self.action12.setText(_translate("MainWindow", "12"))
        self.action13.setText(_translate("MainWindow", "13"))
        self.action14.setText(_translate("MainWindow", "14"))
        self.action15.setText(_translate("MainWindow", "15"))
        self.action16_2.setText(_translate("MainWindow", "16"))
        self.action17.setText(_translate("MainWindow", "17"))
        self.action18.setText(_translate("MainWindow", "18"))
        self.action1.setText(_translate("MainWindow", "19"))
        self.action20.setText(_translate("MainWindow", "20"))
        self.action21.setText(_translate("MainWindow", "21"))
        self.action22.setText(_translate("MainWindow", "22"))
        self.action23.setText(_translate("MainWindow", "23"))
        self.action24.setText(_translate("MainWindow", "24"))
        self.action25.setText(_translate("MainWindow", "25"))
        self.action26.setText(_translate("MainWindow", "26"))
        self.action27.setText(_translate("MainWindow", "27"))
        self.action28.setText(_translate("MainWindow", "28"))
        self.action29.setText(_translate("MainWindow", "29"))
        self.action30.setText(_translate("MainWindow", "30"))
        self.action31.setText(_translate("MainWindow", "31"))
        self.action30_2.setText(_translate("MainWindow", "30"))
        self.action1_2.setText(_translate("MainWindow", "1"))
        self.action_4.setText(_translate("MainWindow", "Другие"))
        self.action_5.setText(_translate("MainWindow", "Масса"))
        self.action_6.setText(_translate("MainWindow", "Длина"))
        self.action_7.setText(_translate("MainWindow", "Площадь"))
        self.action_8.setText(_translate("MainWindow", "Объем"))
        self.action_9.setText(_translate("MainWindow", "Время"))
        self.action_10.setText(_translate("MainWindow", "Скорость"))
        self.action.setText(_translate("MainWindow", "Систем исчисления"))
        self.action_2.setText(_translate("MainWindow", "Масса"))

